version: '3.8'

name: "p7"
services:
  db:
    container_name: db
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: oc_dev
        target: /var/lib/mysql
    ports:
      - "3001:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/vendor
    depends_on:
      - db
    ports:
      - "3000:8000"

volumes:
  oc_dev:
    external: true
  tls:
